-- おみくじデータをDBに移行: daily_fortunesテーブル作成・RLS設定・シードデータ挿入

create table if not exists daily_fortunes (
  id             int primary key,
  rank           text not null,
  rank_name_ja   text not null,
  rank_name_en   text not null,
  poem_ja        text not null,
  poem_en        text not null,
  general_ja     text not null,
  general_en     text not null,
  bond_ja        text not null,
  bond_en        text not null,
  health_ja      text not null,
  health_en      text not null,
  wish_ja        text not null,
  wish_en        text not null,
  blessing_ja    text not null,
  blessing_en    text not null,
  lucky_color_ja text not null,
  lucky_color_en text not null,
  lucky_item_ja  text not null,
  lucky_item_en  text not null,
  lucky_number   int  not null,
  sort_order     int  default 0,
  created_at     timestamptz default now()
);

alter table daily_fortunes enable row level security;

create policy "公開読み取り専用アクセスを許可" on daily_fortunes
  for select using (true);

revoke insert, update, delete on daily_fortunes from anon, authenticated;

insert into daily_fortunes (id, rank, rank_name_ja, rank_name_en, poem_ja, poem_en, general_ja, general_en, bond_ja, bond_en, health_ja, health_en, wish_ja, wish_en, blessing_ja, blessing_en, lucky_color_ja, lucky_color_en, lucky_item_ja, lucky_item_en, lucky_number, sort_order)
values
  (1, 'daikichi', '大吉', 'Great Blessing',
   '花ひらき 笑顔あふれる 祝いの日 光あまねく 道を照らさん',
   'Blossoms unfold on this joyful day of celebration; radiant light illuminates your path ahead.',
   '至高の幸運に恵まれる一日。心からの願いが次々と実を結び、周囲からの温かな祝福と笑顔に包まれます。',
   'A magnificent day blessed with supreme good fortune. Your heartfelt wishes bear fruit surrounded by warmth and smiles.',
   '大切な人との絆が一段と深まります。感謝の言葉を素直に伝えて吉。',
   'Cherished bonds grow even deeper. Expressing sincere gratitude brings immense joy.',
   '気力・体力ともに充実。爽やかな風を感じて散歩すると良い閃きが。',
   'Vitality and energy at their peak. A gentle stroll in the breeze sparks fresh inspiration.',
   '長年温めてきた夢や目標に大きな前進あり。自信を持って進みましょう。',
   'Great strides in long-held dreams and goals. Move forward with confidence.',
   'あなたの生まれたこの特別な日に、世界中から優しい光が降り注ぎます。',
   'On this special day of your birth, gentle light pours down from across the world.',
   '桜色（さくらいろ）', 'Cherry Blossom Pink',
   'バースデーケーキと金箔', 'Birthday Cake & Gold Leaf',
   7, 1),

  (2, 'daikichi', '大吉', 'Great Blessing',
   '雲晴れて 富士の嶺照らす 初日の出 志遥かに 夢羽ばたけり',
   'Clouds part to reveal Mount Fuji bathed in morning sunrise; your noble aspirations take flight.',
   '運気は最高潮。迷いを捨てて新しい挑戦へ踏み出す絶好の契機です。周囲の協力にも恵まれます。',
   'Fortune reaches its zenith. An ideal moment to embark on bold new adventures with supportive allies.',
   '旧友や家族との再会・語らいが、かけがえのない宝物になります。',
   'Reconnecting and talking with old friends or family becomes an irreplaceable treasure.',
   '快眠快食で心身健やか。お祝いのご馳走を笑顔で楽しんで吉。',
   'Great sleep and joyful meals keep spirit vibrant. Enjoy celebratory dishes with smiles.',
   '思い描いた通りの結果が得られる兆し。仲間と共に喜びを分かち合えます。',
   'Signs of achieving exactly what you envisioned. Share the joy with those around you.',
   '重ねてきた年月が美しい年輪となり、今日という日を輝かせています。',
   'The passing years have woven beautiful rings of wisdom, illuminating today with grace.',
   '黄金色（こがねいろ）', 'Imperial Gold',
   'フォトフレームと思い出の写真', 'Photo Frame & Cherished Picture',
   8, 2),

  (3, 'daikichi', '大吉', 'Great Blessing',
   '清流に 錦を映す もみじ葉の 輝く未来 ここに始まり',
   'Reflected like brocade in clear waters, radiant maple leaves mark the dawn of a bright future.',
   'あらゆる巡り合わせが調和する恵みの日。これまでの努力が素晴らしい実を結びます。',
   'A blessed day of harmonious alignment. Past efforts blossom into splendid results.',
   '心通い合う温かい会話から、生涯続く友情や縁が育まれます。',
   'Warm, heartfelt conversations nurture lifelong bonds of genuine friendship.',
   '身体が軽快で意欲満々。趣味や創作活動に没頭するのに最適です。',
   'Body feels light and spirit inspired. Perfect time to immerse in creative arts.',
   '諦めかけていたことに思わぬ好機到来。最後まで信じて吉。',
   'An unexpected breakthrough appears for what seemed challenging. Keep your faith.',
   'いつも周りを笑顔にしてくれるあなたへ、最高の幸せが訪れますように。',
   'To you who always brings smiles to others, may the greatest happiness be yours.',
   '深紅（しんく）', 'Crimson Red',
   '手書きのメッセージカード', 'Handwritten Message Card',
   1, 3),

  (4, 'chukichi', '中吉', 'Middle Blessing',
   '緑なす 若葉そよぐ 朝風に 夢紡ぐ糸 静かに強く',
   'In morning breezes swaying green young leaves, threads of dreams are quietly and strongly spun.',
   '着実な前進と穏やかな喜びに満ちた日。焦らず丁寧に物事を進めることで幸運が定着します。',
   'A day filled with steady progress and serene joy. Moving thoughtfully seals good fortune.',
   '身近な人の長所に気づき、褒め合うことで絆がさらに深まります。',
   'Noticing and praising the virtues of those close to you deepens mutual trust.',
   '温かいハーブティーや緑茶で一息入れるとリフレッシュできます。',
   'Taking a cozy break with herbal or green tea brings wonderful rejuvenation.',
   '一歩一歩の積み重ねが大きな成果へと結実します。計画を大切に。',
   'Step-by-step consistency culminates in grand achievement. Cherish your plans.',
   '新たな一年の幕開けに、たくさんの素晴らしい発見と出会いがありますように。',
   'As your new year unfolds, may it be filled with wonderful discoveries and encounters.',
   '山吹色（やまぶきいろ）', 'Golden Yellow',
   'オルゴール・音楽プレイヤー', 'Music Box & Melody Player',
   3, 4),

  (5, 'chukichi', '中吉', 'Middle Blessing',
   '水面に 映る月影 澄み渡り 静かなる心 宝を宿す',
   'Moonlight reflected on clear waters shines bright; a serene heart harbors timeless treasures.',
   '精神的な充実が得られる良き日。懐かしい思い出を振り返ることで新たな活力を見出せます。',
   'A fulfilling day for the soul. Reflecting on nostalgic memories sparks fresh vitality.',
   '言葉少なでも気持ちが通じ合える安心感に包まれます。',
   'Enveloped in comforting trust where few words are needed to understand each other.',
   'ストレッチや深呼吸でリラックス。姿勢を整えると運気アップ。',
   'Relax with light stretches and deep breathing. Good posture elevates your energy.',
   '助言を素直に受け入れることで、思わぬ近道が見つかります。',
   'Listening open-heartedly to advice reveals unexpected, pleasant shortcuts.',
   'あなたの優しさがいつも周りを温めています。特別な今日を存分に楽しんで。',
   'Your kindness always warms those around you. Enjoy every moment of this special day.',
   '浅葱色（あさぎいろ）', 'Light Azure Blue',
   '和風のしおり・本', 'Traditional Bookmark & Book',
   5, 5),

  (6, 'shokichi', '小吉', 'Small Blessing',
   '野に咲ける 名もなき花の 健気に 香りそっと 心癒やす',
   'Wildflowers blooming gently in the field soothe the heart with their delicate fragrance.',
   '日常の小さな幸せに恵まれる日。ささやかな出来事の中に温かい感動を見つけられます。',
   'A day touched by gentle, everyday joys. Warm inspiration is found in simple moments.',
   'ちょっとしたおすそ分けや気配りが喜ばれ、笑顔が広がります。',
   'Small thoughtful gestures and sharing bring delighted smiles to those around you.',
   'バランスの良い食事と適度な休憩を心がけると吉。',
   'Mindful meals and balanced rest keep you in great harmony.',
   '急がば回れの精神で。基礎を固めることが成功への鍵となります。',
   'Steady patience wins the race. Solid foundations unlock lasting success.',
   '小さな幸せの積み重ねが、やがて大きな喜びの花を咲かせます。',
   'The accumulation of small joys will soon bloom into grand happiness.',
   '抹茶色（まっちゃいろ）', 'Matcha Green',
   '和菓子・お茶', 'Japanese Sweets & Tea',
   6, 6),

  (7, 'shokichi', '小吉', 'Small Blessing',
   '雨上がり 虹の架け橋 空仰ぎ 新たな希望 胸に灯らん',
   'After the rain a rainbow bridges the sky; fresh hope gently kindles within the heart.',
   '停滞していたことが少しずつ動き始める兆し。前向きな気持ちで過ごすと好転します。',
   'Things in stillness begin to gently move. Maintaining an optimistic outlook brings sunny days.',
   '久しぶりの連絡が思わぬ嬉しい展開に発展する予感。',
   'A message from someone after a while sparks a wonderful, pleasant connection.',
   '目や肩を休めてリフレッシュを。お風呂にゆっくり浸かると吉。',
   'Rest your eyes and shoulders. A warm soothing bath restores your energy.',
   '周囲の意見を参考にしながら、自分のペースで進めましょう。',
   'Proceed at your own comfortable pace while taking friendly insights into account.',
   '雨のあとに虹が架かるように、あなたの未来にも輝かしい光が待っています。',
   'Just as rainbows follow the rain, radiant light awaits your bright future.',
   '藤色（ふじいろ）', 'Wisteria Purple',
   '折り紙の花・手紙', 'Origami Flower & Letter',
   2, 7),

  (8, 'kichi', '吉', 'Blessing',
   '松の緑 幾代経ても 変わらじと 変わらぬ愛の 尊きを知る',
   'Evergreen pines remain steadfast through generations, teaching the timeless value of enduring love.',
   '安定した平和な運気。いつも通りの日常がかけがえのない宝物であると実感できる日です。',
   'A peaceful and grounded day. Everyday moments reveal themselves as true treasures.',
   '昔からの親しい間柄の人と、変わらない安心感を分かち合えます。',
   'Share comforting, unchanging warmth with longtime close companions.',
   '規則正しい生活リズムを守ることで、体調良好をキープ。',
   'Maintaining a regular daily rhythm keeps health and vitality well-balanced.',
   '現状を丁寧に維持・改善していくことで、確実な実りへとつながります。',
   'Polishing and nurturing present efforts leads to certain, fruitful rewards.',
   '変わらない絆と温かい愛情に包まれて、穏やかな一年をお過ごしください。',
   'Surrounded by enduring bonds and heartfelt love, may your year be peaceful and bright.',
   '萌黄色（もえぎいろ）', 'Fresh Sprout Green',
   '記念切手・ノート', 'Commemorative Stamp & Journal',
   4, 8),

  (9, 'kichi', '吉', 'Blessing',
   '竹の節 伸びゆくごとに 節固く 試練も糧に 強く育たん',
   'With each joint bamboo grows taller and sturdier; every trial becomes strength for growth.',
   '節目の日を迎えて気持ちを新たにする好機。過去の経験がすべて力になっていると実感できます。',
   'A milestone moment to renew spirit. You will feel that all past experiences are your strength.',
   '互いに切磋琢磨し合える良き仲間に恵まれます。',
   'Blessed with wonderful peers who inspire and elevate each other.',
   '適度な運動を取り入れると活力が湧いてきます。',
   'Incorporating moderate exercise brings an invigorating surge of vitality.',
   '初心を忘れずに取り組むことで、確実な道が開けていきます。',
   'Remembering your initial passion opens a steady and dependable path forward.',
   '一つ歳を重ねるごとに、あなたの魅力と深みがいっそう増していきます。',
   'With every passing year, your charm, depth, and beauty grow even brighter.',
   '瑠璃色（るりいろ）', 'Lapis Lazuli Blue',
   'お気に入りの万年筆・ペン', 'Favorite Pen & Stationery',
   9, 9),

  (10, 'suekichi', '末吉', 'Future Blessing',
   '冬枯れの 枝にもやがて 春立ちて 蕾ふくらみ 花咲く日待つ',
   'On winter branches spring will soon arrive; buds swell quietly, waiting for the day of bloom.',
   'これから徐々に運気が上向いていく吉兆。今はじっくり種を蒔き、準備を整える時期です。',
   'An auspicious sign of rising fortunes ahead. A rewarding time for quiet preparation and planting seeds.',
   '時間をかけて少しずつ信頼を育むことで、強固な関係が築けます。',
   'Taking time to gently nurture trust builds unbreakable, long-lasting relationships.',
   '体を冷やさないように温かくして過ごすと調子が整います。',
   'Staying warm and cozy helps keep your body and mind in optimal balance.',
   '焦りは禁物。時が満ちれば自然と良い結果に結びつきます。',
   'Patience is your ally. When the time is ripe, things will naturally flourish.',
   '未来のあなたが笑顔で振り返ることができるよう、今日の一歩を大切に。',
   'Cherish today''s step so that your future self can look back with a radiant smile.',
   '撫子色（なでしこいろ）', 'Dianthus Pink',
   'あたたかいブランケット', 'Cozy Warm Blanket',
   10, 10),

  (11, 'suekichi', '末吉', 'Future Blessing',
   '小川ゆく 水の流れは 淀みなく やがて大海 辿り着くらむ',
   'The stream flows forward without hesitation, destined in time to meet the grand ocean.',
   '今は小さな一歩でも、やがて大きな海へと注ぐように成果が広がっていきます。',
   'Even small steps today will widen into vast oceans of achievement over time.',
   '相手の話にじっくり耳を傾けることで、誤解が解けて和やかになります。',
   'Listening patiently to others dissolves misunderstandings and restores harmony.',
   '無理をせず、自分のペースを崩さないことが健康の秘訣。',
   'Not overexerting yourself and honoring your natural pace is the key to well-being.',
   '後半に向けて運気上昇。粘り強さが大きな武器となります。',
   'Fortunes rise as days progress. Resilience and perseverance are your greatest assets.',
   'あなたの歩んできた道はすべて未来の輝く宝物につながっています。',
   'Every step of your journey leads to radiant treasures in the future.',
   '茜色（あかねいろ）', 'Sunset Madder Orange',
   'ランタン・キャンドル', 'Lantern & Candle',
   11, 11),

  (12, 'hankichi', '半吉', 'Half Blessing',
   '半ば咲く 花も風情の ありにけり 満ちゆく月を 楽しむ心地',
   'Half-bloomed blossoms possess their own poetic elegance, like watching the waxing moon grow full.',
   '伸びしろと可能性に満ちた状態。完璧を求めすぎず、途中のプロセスを楽しむと吉。',
   'A state filled with boundless potential and growth. Savor the process rather than seeking perfection.',
   'お互いの違いを認め合うことで、新しい発見と面白さが生まれます。',
   'Embracing each other''s differences brings fresh discoveries and delightful perspectives.',
   '気分転換にお気に入りの音楽を聴いたり、ゲームを楽しんだりして吉。',
   'Listening to favorite melodies or playing interactive mini-games refreshes your mood.',
   '半分叶ったことを喜び、残り半分をこれからの楽しみに取っておきましょう。',
   'Celebrate the half already achieved, and look forward to the other half with joyful anticipation.',
   '完璧でなくていい、ありのままのあなたが一番輝いています。お誕生日おめでとう！',
   'You do not need to be perfect—being your authentic self is what shines brightest. Happy Birthday!',
   '若竹色（わかたけいろ）', 'Young Bamboo Green',
   'パズル・おもちゃ', 'Puzzle & Wooden Toy',
   12, 12)

on conflict (id) do update set
  rank           = excluded.rank,
  rank_name_ja   = excluded.rank_name_ja,
  rank_name_en   = excluded.rank_name_en,
  poem_ja        = excluded.poem_ja,
  poem_en        = excluded.poem_en,
  general_ja     = excluded.general_ja,
  general_en     = excluded.general_en,
  bond_ja        = excluded.bond_ja,
  bond_en        = excluded.bond_en,
  health_ja      = excluded.health_ja,
  health_en      = excluded.health_en,
  wish_ja        = excluded.wish_ja,
  wish_en        = excluded.wish_en,
  blessing_ja    = excluded.blessing_ja,
  blessing_en    = excluded.blessing_en,
  lucky_color_ja = excluded.lucky_color_ja,
  lucky_color_en = excluded.lucky_color_en,
  lucky_item_ja  = excluded.lucky_item_ja,
  lucky_item_en  = excluded.lucky_item_en,
  lucky_number   = excluded.lucky_number,
  sort_order     = excluded.sort_order;
